### ISSUE TITLE
Session collection becoming really huge in DB

### ISSUE THREAD

**Issue by mayeaux** [sahat/hackathon-starter#730]
Hi there,

I've been playing around with this, and before too long I have over 500k sessions in my DB, coming out to over 100MB.

How can I reduce the amount of sessions in the DB? Can I limit it to one session per user or something? Thanks!

**Comment by niallobrien** [comment]
@mayeaux This was something I mentioned in a previous issue. I'm not entirely sure of the best solution here either. Obviously using Redis or something would be a better long-term solution, but not everyone wants to maintain Redis on top of everything else. I suppose you could manually run a query to empty the collection from Mongo or run this query when the server restarts and has established a connection to Mongo. Any other ideas?

**Comment by mayeaux** [comment]
Well, since I changed my rule for expiring cookies the document count has fallen to 130k and none of them look expired, so maybe the library itself eliminates them? Worth looking into.

**Comment by brennhill** [comment]
@mayeaux I will file this as a seperate issue but realistically it would be best to move to JWT authentication instead of cookies and seesions.

Another option is to just have  scheduled job/timeout that queries old sessions and deletes them.  That's just a few lines of code.

**Comment by alangibson** [comment]
JWT would be awesome. I actually hacked it in to a project I'm working on. Unfortunately, it seems to have been ruled out in #353

**Comment by brennhill** [comment]
That's unfortunate

On Dec 10, 2017 8:32 PM, "Alan Gibson" <notifications@github.com> wrote:

JWT would be awesome. I actually hacked it in to a project I'm working on.
Unfortunately, it seems to have been ruled out in #353
<https://github.com/sahat/hackathon-starter/issues/353>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/sahat/hackathon-starter/issues/730#issuecomment-350548676>,
or mute the thread

**Comment by YasharF** [comment]
I am trying to see what is actionable on this thread.  So JWT as an option is out per reasoning in https://github.com/sahat/hackathon-starter/issues/353 .  The entries in the session DB also do seem to get cleaned up when expired.  Are we OK to close this issue?

@mayeaux can you comment on what change you made in your rule for expiring cookies?  I am wondering if that is something that should be more of a default or not.

**Comment by YasharF** [comment]
It turns out that since the session was only being stored in the server-side, every time that a user revisited the site if they had closed the browser, a new session would get generated.  This resulted in the old session becoming orphaned till its automatic deletion by MongoDB two weeks after its last use.

This is now fixed with https://github.com/sahat/hackathon-starter/commit/e9f0e8e673cbf9b0f8dd0aef808da14403ab3b4b

**Comment by mshd** [comment]
I still have the problem in 2021.
![Screenshot from 2021-04-17 12-24-02](https://user-images.githubusercontent.com/17379661/115101561-d47fc500-9f77-11eb-8c94-4acb18615ec2.png)
Can I just delete the table once in a while?

**Comment by mayeaux** [comment]
Turns out that most of these sessions are not really needed since they don't store much pertinent user data. If all you care about is logins you can (in my opinion, check for yourself) safely delete all the sessions that don't store passport data.

`db.getCollection('sessions').remove({ session: { $not: /.*passport.*/i  }  })`

This query will delete all sessions that don't have passport data. May want to do a dry run first, I'm not responsible for the data you delete lol
